# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: storytold.pdfcraft
PackageVersion: 0.4.0
PackageLocale: en-US
Publisher: artcraft
PublisherUrl: https://github.com/storytold
PublisherSupportUrl: https://github.com/storytold/pdfcraft/issues
PackageName: PdfCraft
PackageUrl: https://github.com/storytold/pdfcraft
License: Apache-2.0
ShortDescription: An open-source, clean-room reimplementation of Adobe Acrobat built in pure Rust
Tags:
- acrobat
- acrobat-full
- acrobat-pro
- adobe
- adobe-acrobat
- document-processing
- documents
- pdf
- pdf-generation
- pdf-processing
- pdf-tools
- pdf-viewer
- rust
ReleaseNotesUrl: https://github.com/storytold/pdfcraft/releases/tag/v0.4.0
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/storytold/pdfcraft/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
