# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: storytold.pdfcraft
PackageVersion: 0.4.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/storytold/pdfcraft/releases/download/v0.4.0/pdfcraft-0.4.0-windows-x64.msi
  InstallerSha256: 76E61E2791CAB97273C0D900DC95411C1114699386E9C381A07E5FE31A643E3A
  ProductCode: '{5F056693-2240-48D6-A44A-B7BC5EBF819A}'
- Architecture: x86
  InstallerUrl: https://github.com/storytold/pdfcraft/releases/download/v0.4.0/pdfcraft-0.4.0-windows-x86.msi
  InstallerSha256: 1FB6F55AC82BAD3E268F8F1AF4D0DBC64F0F27F2817E505BF4F94971B0AAB4D7
  ProductCode: '{43E8495F-330F-4759-B8B8-9D5353511B6B}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-08
